### ISSUE TITLE
How to handle the frames at the beginning and end of the video?

### ISSUE THREAD

**Issue by Songinpyo** [hongsukchoi/TCMR_RELEASE#35]
Hi,
First of all, thank you for the good research that inspires me.

I have a question about data loader.

The TCMR loads 16 frames and predicts the middle frame, but I don't know how can we load 16 frames with the same target in the middle at the beginning or end of the video.

So, I was wondering if TCMR drops the 8 frames at the beginning and the end, but when I ran the demo, it seemed that prediction was possible in the entire frame without any discarded frames.

I wonder how you are handling this part.
Is the loading method different between training and inference?

I look forward to your response. Thank you!

**Comment by hongsukchoi** [comment]
Hi,

I think I didn't handle them in my demo code. But for the evaluation on 3DPW, I copied the frame to do padding and match the input length.

**Comment by dw444** [comment]
Hi,
Thank you for your work.
So, during training you only use 1 frame per 16 frames in order to train the model, dropping the rest, while during evaluation you do padding to predict the parameters for each frame?
Besides, did you consider using some other method, such as sliding window, in order to use all frames and boost the network performance?
Finally, how can your demo code produce predictions for all frames if you do not use padding there?
Thanks in advance.

**Comment by Songinpyo** [comment]
Thanks for your kind replies
